name: Build SDK Code
on: [push]
jobs:
  Build-Xcode-Project:
   runs-on: macOS-latest
   steps:
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
    - name: Xcode Version
      run: /usr/bin/xcodebuild -version
